apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: pulsate-hello
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- literals:
  - KEY=value
  name: pulsate-hello
