services:
  db:
    image: postgres:16
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pulsate
      - POSTGRES_PASSWORD=pulsate_db_pass
  kv:
    image: valkey/valkey
    container_name: kv
    ports:
      - "6379:6379"
    volumes:
      - kv_data:/data


volumes:
  db_data:
  kv_data:
