name: "Bug report"
description: "Create a report on bugs you find"
labels:
  - "T: bug (unconfirmed)"

body:
  - type: checkboxes
    id: confirmation
    attributes:
      label: Before reporting
      description: Before reporting, you have to check follows
      options:
        - label: Checked [same issue](https://github.com/approvers/pulsate/issues?q=) already has not already been reported
          required: true
        - label: Checked this issue is not a security issue. If it is a security issue, follow [this](https://github.com/approvers/pulsate/tree/main/SECURITY.md).
          required: true
  - type: input
    id: version
    attributes:
      label: Pulsate Version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happening
      description: Please provide details of the bug (or what you believe to be an out-of-specification event) that is occurring.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      description: Operations performed and events that occurred when the problem occurred.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Please provide logs if available
    validations:
      required: false
  - type: textarea
    attributes:
      label: System Info
      description: Information on Docker and various language execution environment versions and operating systems
  - type: textarea
    attributes:
      label: Any additional comments?
