name: "Feature request"
description: "Create a feature request"
labels:
  - "T: feature"

body:
  - type: checkboxes
    id: confirmation
    attributes:
      label: Before requesting
      description: Before requesting, you have to check follows
      options:
        - label: Checked [same request](https://github.com/pulsate-dev/pulsate/issues?q=) already has not already been reported
          required: true
        - label: Understand that this request is not certain to be adopted.
          required: true
  - type: textarea
    attributes:
      label: Problem
      description: Please describe the problem you want to solve.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Please describe how you would like to solve this problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other information
