name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Run install
        run: |
          pnpm i --frozen-lockfile

      - name: Run type checks
        run: |
          pnpm check:type

      - name: Run fmt
        run: |
          pnpm format:check

      - name: Run lint
        run: |
          pnpm lint

      - name: Run test
        run: |
          pnpm test:coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
