name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Run install
        run: |
          pnpm i --frozen-lockfile

      - name: Run type checks
        run: |
          pnpm check:type

      - name: Run fmt
        run: |
          pnpm check:format

      - name: Run lint
        run: |
          pnpm lint

      - name: Run ls-lint
        run: |
          pnpm check:filename

      - name: Run test
        run: |
          pnpm test:coverage

      - name: Run build
        run: |
          pnpm build

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
