name: node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: "8"

      - name: Run install
        run: |
          pnpm i --frozen-lockfile

      - name: Run fmt
        run: |
          pnpm format

      - name: Run lint
        run: |
          pnpm lint

      - name: Run test
        run: |
          pnpm test
